//try to build login screens? useState for username and passwords

// import images etc here

// {
//     id: 0,
//     parentId: null,
//     name: "sol",
//     image: "placeholder",
//     type: "placeholder (star/planet/dwarf planet/asteroid/moon/etc)",
//     subtype: "placeholder (spectral class/terrestrial/gas/etc)",
//     distanceToParent: ["units", "val"]
//     mass: "placeholder",
//     diameter: "placeholder",
//     gravity: "placeholder",
//     meanTemp: "placeholder (deg C)",
//     surfPressure: "placeholder (kPa)",
//     rotPeriod: "placeholder (sidereal) (earth days)",
//     orbitPeriod: "placeholder (relative to parent)",
//     eccentricity: "placeholder",
//     description: "placeholder"
// }

export const CELESTIALS = [
    {
        id: 0,
        parentId: null, //effectively Sagittarius A*
        name: "sol",
        image: "placeholder",
        type: "star",
        subtype: "g-type main-sequence star",
        distanceToParent: ["ly", "2.6E4"],
        mass: "2E30", //2*10^30 kg
        diameter: 1400000, //km
        gravity: 274.0,
        meanTemp: 5500, //photosphere
        surfPressure: "8.68E-2", //kPa
        rotPeriod: 27, //at equator
        orbitPeriod: "230 million years",
        eccentricity: null,
        description: "placeholder"
    },
    {
        id: 1,
        parentId: 0,
        name: "mercury",
        image: "placeholder",
        type: "planet",
        subtype: "terrestrial planet",
        distanceToParent: ["au", 0.4],
        mass: "3.3E23",
        diameter: 4880,
        gravity: 3.7,
        meanTemp: 167,
        surfPressure: "placeholder (kPa)",
        rotPeriod: 58.65,
        orbitPeriod: "placeholder (relative to parent)",
        eccentricity: "placeholder",
        description: "placeholder"
    },
    {
        id: 2,
        parentId: 0,
        name: "venus",
        image: "placeholder",
        type: "planet",
        subtype: "terrestrial planet",
        distanceToParent: "placeholder",
        mass: "placeholder",
        diameter: "placeholder",
        gravity: "placeholder",
        meanTemp: "placeholder (deg C)",
        surfPressure: "placeholder (kPa)",
        rotPeriod: "placeholder (sidereal) (earth days)",
        orbitPeriod: "placeholder (relative to parent)",
        eccentricity: "placeholder",
        description: "placeholder"
    },
    {
        id: 3,
        parentId: 0,
        name: "earth",
        image: "placeholder",
        type: "planet",
        subtype: "terrestrial planet",
        distanceToParent: ["au", 1],
        mass: "placeholder",
        diameter: "placeholder",
        gravity: 9.81,
        meanTemp: "placeholder (deg C)",
        surfPressure: "placeholder (kPa)",
        rotPeriod: "placeholder (sidereal) (earth days)",
        orbitPeriod: "placeholder (relative to parent)",
        eccentricity: "placeholder",
        description: "placeholder"
    },
    {
        id: 4,
        parentId: 0,
        name: "mars",
        image: "placeholder",
        type: "planet",
        subtype: "terrestrial planet",
        distanceToParent: "placeholder",
        mass: "placeholder",
        diameter: "placeholder",
        gravity: "placeholder",
        meanTemp: "placeholder (deg C)",
        surfPressure: "placeholder (kPa)",
        rotPeriod: "placeholder (sidereal) (earth days)",
        orbitPeriod: "placeholder (relative to parent)",
        eccentricity: "placeholder",
        description: "placeholder"
    },
    {
        id: 5,
        parentId: 0,
        name: "jupiter",
        image: "placeholder",
        type: "planet",
        subtype: "gas giant",
        distanceToParent: "placeholder",
        mass: "placeholder",
        diameter: "placeholder",
        gravity: "placeholder",
        meanTemp: "placeholder (deg C)",
        surfPressure: "placeholder (kPa)",
        rotPeriod: "placeholder (sidereal) (earth days)",
        orbitPeriod: "placeholder (relative to parent)",
        eccentricity: "placeholder",
        description: "placeholder"
    },
    {
        id: 6,
        parentId: 0,
        name: "saturn",
        image: "placeholder",
        type: "planet",
        subtype: "gas giant",
        distanceToParent: "placeholder",
        mass: "placeholder",
        diameter: "placeholder",
        gravity: "placeholder",
        meanTemp: "placeholder (deg C)",
        surfPressure: "placeholder (kPa)",
        rotPeriod: "placeholder (sidereal) (earth days)",
        orbitPeriod: "placeholder (relative to parent)",
        eccentricity: "placeholder",
        description: "placeholder"
    },
    {
        id: 7,
        parentId: 0,
        name: "uranus",
        image: "placeholder",
        type: "planet",
        subtype: "gas giant",
        distanceToParent: "placeholder",
        mass: "placeholder",
        diameter: "placeholder",
        gravity: "placeholder",
        meanTemp: "placeholder (deg C)",
        surfPressure: "placeholder (kPa)",
        rotPeriod: "placeholder (sidereal) (earth days)",
        orbitPeriod: "placeholder (relative to parent)",
        eccentricity: "placeholder",
        description: "placeholder"
    },
    {
        id: 8,
        parentId: null,
        name: "neptune",
        image: "placeholder",
        type: "planet",
        subtype: "gas giant",
        distanceToParent: "placeholder",
        mass: "placeholder",
        diameter: "placeholder",
        gravity: "placeholder",
        meanTemp: "placeholder (deg C)",
        surfPressure: "placeholder (kPa)",
        rotPeriod: "placeholder (sidereal) (earth days)",
        orbitPeriod: "placeholder (relative to parent)",
        eccentricity: "placeholder",
        description: "placeholder"
    },
    {
        id: 9,
        parentId: 0,
        name: "pluto",
        image: "placeholder",
        type: "dwarf planet",
        subtype: "",
        distanceToParent: "placeholder",
        mass: "placeholder",
        diameter: "placeholder",
        gravity: "placeholder",
        meanTemp: "placeholder (deg C)",
        surfPressure: "placeholder (kPa)",
        rotPeriod: "placeholder (sidereal) (earth days)",
        orbitPeriod: "placeholder (relative to parent)",
        eccentricity: "placeholder",
        description: "placeholder"
    },
    {
        id: 10,
        parentId: 9,
        name: "charon",
        image: "placeholder",
        type: "moon",
        subtype: "",
        distanceToParent: "placeholder",
        mass: "placeholder",
        diameter: "placeholder",
        gravity: "placeholder",
        meanTemp: "placeholder (deg C)",
        surfPressure: "placeholder (kPa)",
        rotPeriod: "placeholder (sidereal) (earth days)",
        orbitPeriod: "placeholder (relative to parent)",
        eccentricity: "placeholder",
        description: "placeholder"
    },
    {
        id: 11,
        parentId: 3,
        name: "moon",
        image: "placeholder",
        type: "moon",
        subtype: "placeholder (spectral class/terrestrial/gas/etc)",
        distanceToParent: "placeholder",
        mass: "placeholder",
        diameter: "placeholder",
        gravity: "placeholder",
        meanTemp: "placeholder (deg C)",
        surfPressure: "placeholder (kPa)",
        rotPeriod: "placeholder (sidereal) (earth days)",
        orbitPeriod: "placeholder (relative to parent)",
        eccentricity: "placeholder",
        description: "placeholder"
    }
];